surface.CreateFont( "COOP_FONT_HUD_1", 
{
	font = "coolvetica",
	size = 40,
	weight = 700,
	blursize = 10,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = false,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = true,
} )

surface.CreateFont( "COOP_FONT_HUD_2", 
{
	font = "coolvetica",
	size = 43,
	weight = 430,
	blursize = 5,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = true,
	symbol = false,
	rotary = false,
	shadow = false,
	additive = false,
	outline = false,
} )

surface.CreateFont( "COOP_FONT_HUD_3", 
{
	font = "coolvetica",
	size = 43,
	weight = 400,
	blursize = 0,
	scanlines = 0,
	antialias = true,
	underline = false,
	italic = false,
	strikeout = true,
	symbol = false,
	rotary = false,
	shadow = true,
	additive = false,
	outline = false,
} )